### ISSUE TITLE
Widget not loading in VS Code

### ISSUE THREAD

**Issue by nikhilmaddirala** [yWorks/yfiles-jupyter-graphs#54]
Widget not loading in VS Code. Works fine in Jupyter server in browser, but gives this error in VS Code:

```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'GraphModel' from module 'yfiles-jupyter-graphs'
Error: No version of module yfiles-jupyter-graphs is registered
    at ph.loadClass (https://vscode-remote+codespaces-002bcongenial-002deureka-002dj75x77rxv9hqqq6.vscode-resource.vscode-cdn.net/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-renderers-1.0.18/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4099813)
    at ph.loadClass (https://vscode-remote+codespaces-002bcongenial-002deureka-002dj75x77rxv9hqqq6.vscode-resource.vscode-cdn.net/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-renderers-1.0.18/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4403287)
    at ph.loadModelClass (https://vscode-remote+codespaces-002bcongenial-002deureka-002dj75x77rxv9hqqq6.vscode-resource.vscode-cdn.net/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-renderers-1.0.18/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4097773)
    at ph._make_model (https://vscode-remote+codespaces-002bcongenial-002deureka-002dj75x77rxv9hqqq6.vscode-resource.vscode-cdn.net/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-renderers-1.0.18/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4094616)
    at ph.new_model (https://vscode-remote+codespaces-002bcongenial-002deureka-002dj75x77rxv9hqqq6.vscode-resource.vscode-cdn.net/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-renderers-1.0.18/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4092246)
    at ph.handle_comm_open (https://vscode-remote+codespaces-002bcongenial-002deureka-002dj75x77rxv9hqqq6.vscode-resource.vscode-cdn.net/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-renderers-1.0.18/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4091039)
    at https://vscode-remote+codespaces-002bcongenial-002deureka-002dj75x77rxv9hqqq6.vscode-resource.vscode-cdn.net/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-renderers-1.0.18/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4402511
    at n._handleCommOpen (https://vscode-remote+codespaces-002bcongenial-002deureka-002dj75x77rxv9hqqq6.vscode-resource.vscode-cdn.net/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js:3:80955)
    at async n._handleMessage (https://vscode-remote+codespaces-002bcongenial-002deureka-002dj75x77rxv9hqqq6.vscode-resource.vscode-cdn.net/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js:3:82830)
```

![image](https://github.com/user-attachments/assets/babbb2e7-1a7f-4d84-9961-027c0f06318c)

![image](https://github.com/user-attachments/assets/9d4ada79-bef8-4247-9135-b4eaa5afa2f0)

**Comment by yGuy** [comment]
What exact version of VS Code ist this?

**Comment by fskpf** [comment]
I can reproduce it locally. VSCode looks for `/yfiles-jupyter-graphs/index.js`, although it is installed in `/yfiles_jupyter_graphs/index.js`:

![dashes-vs-underscore](https://github.com/user-attachments/assets/0169939c-ea74-45f0-9b52-54658b9c7adc)

I'm not sure if this is related to a change in VSCode because it used to work in the past and I'm not aware of any change regarding this on our side.

**Comment by nikhilmaddirala** [comment]
> I've just deployed a new version (`v1.7.3`) which should fix this problem. Unfortunately, VSCode needs some convincing to load the new version. The following steps did the trick for me:
> 
> First, reload the VSCode window with `F1` -> `Developer: Reload Window`. Otherwise, it may think that there is no new version at all.
> 
> Then, modify the pip install cell like so
> 
> ```
> %pip install yfiles_jupyter_graphs==1.7.3
> ```
> 
> and run the cell to update the version explicitly. Alternatively, you can update/install it also directly in your Python environment with `pip install yfiles-jupyter-graphs --upgrade` from the command line. The important part here is that you need to install the new version in the Python environment that runs your notebook in VSCode.
> 
> Then, you need to reload the window again (`F1` -> `Developer: Reload Window`), otherwise VSCode uses the old version from its cache. So this step is essential after installing the new version. Eventually, VSCode picks up the new version, but this forces a reload.
> 
> After that, you can `Run All` and it loads the new working version 1.7.3.
> 
> Please let me know if this works on your end as well.

@fskpf - Thank you so much, it's working for me now! 🙏 😊
