### ISSUE TITLE
Failed to load model class 'GraphModel' in jupyter lite

### ISSUE THREAD

**Issue by DylanShang** [yWorks/yfiles-jupyter-graphs#55]
code in [jupyter-lite](https://jupyterlite.readthedocs.io/en/stable/_static/lab/index.html)
```
%pip install yfiles_jupyter_graphs==1.7.3
from yfiles_jupyter_graphs import GraphWidget
GraphWidget()
```
Error information
```
Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'GraphModel' from module 'yfiles-jupyter-graphs'
Error: No version of module yfiles-jupyter-graphs is registered
    at f.loadClass (https://jupyterlite.readthedocs.io/en/stable/_static/extensions/@jupyter-widgets/jupyterlab-manager/static/446.fdf8b1b233cb8c1783f6.js?v=fdf8b1b233cb8c1783f6:1:74920)
    at f.loadModelClass (https://jupyterlite.readthedocs.io/en/stable/_static/extensions/@jupyter-widgets/jupyterlab-manager/static/327.68dbf8491690b3aff1e7.js?v=68dbf8491690b3aff1e7:1:10729)
    at f._make_model (https://jupyterlite.readthedocs.io/en/stable/_static/extensions/@jupyter-widgets/jupyterlab-manager/static/327.68dbf8491690b3aff1e7.js?v=68dbf8491690b3aff1e7:1:7517)
    at f.new_model (https://jupyterlite.readthedocs.io/en/stable/_static/extensions/@jupyter-widgets/jupyterlab-manager/static/327.68dbf8491690b3aff1e7.js?v=68dbf8491690b3aff1e7:1:5137)
    at f.handle_comm_open (https://jupyterlite.readthedocs.io/en/stable/_static/extensions/@jupyter-widgets/jupyterlab-manager/static/327.68dbf8491690b3aff1e7.js?v=68dbf8491690b3aff1e7:1:3894)
    at _handleCommOpen (https://jupyterlite.readthedocs.io/en/stable/_static/extensions/@jupyter-widgets/jupyterlab-manager/static/446.fdf8b1b233cb8c1783f6.js?v=fdf8b1b233cb8c1783f6:1:73457)
    at f._handleCommOpen (https://jupyterlite.readthedocs.io/en/stable/_static/build/jlab_core.3e62503.js:1:5918649)
    at async f._handleMessage (https://jupyterlite.readthedocs.io/en/stable/_static/build/jlab_core.3e62503.js:1:5920543)
```
Related issue:
#50

**Comment by DylanShang** [comment]
> [Because the pip you are running there is not necessarily connected to the Python that runs your notebook.](https://github.com/yWorks/yfiles-jupyter-graphs/issues/50#issuecomment-2186396445) For an in-depth explanation, see https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter

solution:
Add yfiles_jupyter_graphs dependency in `requirements.txt`

**Comment by fskpf** [comment]
Glad that you got it working. 

From my experience, installing it with `%pip install` in the cell should work, when the kernel is restarted afterward (the restart is mandatory).
Have you tried to restart the kernel afterward? Maybe you restarted it to add the dependency in `requirements.txt` although the restart is the actual "fix". Anyway, adding it as dependency is also a good solution.

**Comment by DylanShang** [comment]
Hi @fskpf, thanks for your reply
Since JupyterLite is powered by WebAssembly-based Python, each session is stateless, meaning newly installed libraries cannot be persistently added to the kernel. Therefore, adding the libraries to requirements.txt might be the only viable solution.
